import Head from "next/head";
import Navbar from "../components/common/Navbar";
import Header from "../components/hooks/Header";
import About from "../components/hooks/About";
import LatestProduct from "../components/hooks/LatestProduct";
import MostPopular from "../components/hooks/MostPopular";
import RecommendedProducts from "../components/hooks/RecommendedProducts";
import Footer from "../components/common/Footer";
import AdsBanner from "../components/hooks/AdsBanner";

export default function Home() {
 return (
  <>
   <Head>
    <title>vendorspace-fashion-theme</title>
    <meta
     name="description"
     content="Generated by create next app"
    />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <div>
    {/* Navbar Component */}
    <Navbar />
   </div>

   <div>
    {/* Header Component */}
    <Header />
   </div>

   <div>
    {/* About Component */}
    <About />
   </div>

   <div>
    {/* Latest Product Component */}
    <LatestProduct title="New Arrivals" />
   </div>

   <div>
    {/* Most Popular Component */}
    <MostPopular title="Most Popular" />
   </div>

   <div>
    {/* AdsBanner Component */}
    <AdsBanner />
   </div>

   <div>
    {/* Recommended Product Component */}
    <RecommendedProducts title="Recommended Product" />
   </div>

   <div>
    {/* Recommended Product Component */}
    <RecommendedProducts title="Featured Product" />
   </div>

   <div>
    {/* Footer */}
    <Footer />
   </div>

   <style jsx global>{`
    html,
    body {
     padding: 0;
     margin: 0;
     font-family: "Assistant", sans-serif;
    }
    ,
    * {
     box-sizing: border-box;
    }

    fieldset label span {
     min-width: 125px;
    }
    fieldset .select::after {
     content: "";
     position: absolute;
     width: 9px;
     height: 5px;
     right: 20px;
     top: 50%;
     margin-top: -2px;
     background-image: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='9' height='5' viewBox='0 0 9 5'><title>Arrow</title><path d='M.552 0H8.45c.58 0 .723.359.324.795L5.228 4.672a.97.97 0 0 1-1.454 0L.228.795C-.174.355-.031 0 .552 0z' fill='%23CFD7DF' fill-rule='evenodd'/></svg>");
     pointer-events: none;
    }

    .blog-background {
     background-position: center;
     background-repeat: no-repeat;
     background-size: cover;
    }
   `}</style>
  </>
 );
}
